### PR TITLE
Adding TileStitcher as optional postprocessing tool

### PR DESCRIPTION
**Pull request by thiloSchlemmer**
For now, performance of TileStitcher is stabilized at factor 0.3 (3 times faster) of previous pull request. 
Test-resources reduced and simplified, TestCoverage closer on the level of the master-branch

### CODE REVIEW

**Comment by loicgasser** [comment]
Thank you for the effort! I will have a look at it as soon as possible. Still think we would be better of doing it durong the tile creation, but this could solve a lot of use cases so I will defenetly take the time to review.
Don't hesitate to add some doc!

**Comment by loicgasser** [comment]
Also we should mark it as experimental in the code doc if possible.

**Comment by loicgasser** [comment]
Are you familiar with git rebase? Try to cleanup a bit the commit history and remove my commits.

https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by thiloSchlemmer** [comment]
Hi loic

i have reset my fork, as rebasing seems to be more complicate and all the polluting commits of mine don't give any additional value. I'm not enough experienced in rebasing so commiting my changes to a fresh fork was easier, the new pull request will follow.

After holiday i will add some doc.

**Pull request closed without merging**
